services:
  api:
    build: .
    container_name: fastapi_app
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8080"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: fastapi_redis
    restart: unless-stopped

volumes:
  db_data: